//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPrueba.Models
{
    using AutoMapper;
    using System;
    using System.Collections.Generic;
    using WebApplicationPrueba.ViewModels;


    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.UsuarioProyecto = new HashSet<UsuarioProyecto>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
            
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioProyecto> UsuarioProyecto { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
        public ICollection<long> SelectedUsers { get; set; }

        public void EditProyect(ProyectoViewModel proyectoVM)
        {
            Proyecto proyecto = new Proyecto();
            using (Formacion_DesarrolloEntities context = new Formacion_DesarrolloEntities())
            {
                proyecto = Mapper.Map<Proyecto>(proyectoVM);
                context.Proyecto.Attach(proyecto);
                context.Entry(proyecto).State = System.Data.Entity.EntityState.Modified;
                context.SaveChanges();
            }

            using (Formacion_DesarrolloEntities context = new Formacion_DesarrolloEntities())
            {
                
                
                proyecto.UsuarioProyecto.Clear();
                
            }

        }
    }
}
